---
apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: "enabled"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
  labels:
    aws-observability: "enabled"
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match   *
        region REPLACE_ME_REGION
        log_group_name /aws/eks/REPLACE_ME_CLUSTER_NAME/fargate
        log_stream_prefix n8n-
        auto_create_group true
  filters.conf: |
    [FILTER]
        Name kubernetes
        Match   kube.*
        Merge_Log On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
  parsers.conf: |
    [PARSER]
        Name crio
        Format regex
        Regex ^(?<time>[^ ]+ [^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
