---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: REPLACE_ME_CLUSTER_NAME
  region: REPLACE_ME_REGION
  version: "1.33"
iam:
  withOIDC: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
fargateProfiles:
  - name: n8n-fargate
    selectors:
      - namespace: n8n
  - name: system
    selectors:
      - namespace: kube-system
      - namespace: kube-system
        labels:
          app.kubernetes.io/name: metrics-server
