apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: n8n
  namespace: n8n
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: n8n
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledValues: RequestsAndLimits
        minAllowed:
          cpu: 500m
          memory: 1Gi
        maxAllowed:
          cpu: "4"
          memory: 8Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: n8n-worker
  namespace: n8n
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: n8n-worker
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledValues: RequestsAndLimits
        minAllowed:
          cpu: 500m
          memory: 1Gi
        maxAllowed:
          cpu: "4"
          memory: 8Gi
